### ISSUE TITLE
Product 新增時不會檢查 price 是不是數字

### ISSUE THREAD

**Issue by YJack0000** [CeranaTeam/cloud-function#40]
@Lanznx 
<img width="338" alt="Screen Shot 2022-12-08 at 2 57 17 AM" src="https://user-images.githubusercontent.com/49984479/206271199-11d2ec2b-d09f-42d8-82a1-a6ee7ce49086.png">

**Comment by Lanznx** [comment]
https://github.com/CeranaTeam/cloud-function/pull/41
