### ISSUE TITLE
Discount 要檢查是正數才給過

### ISSUE THREAD

**Issue by YJack0000** [CeranaTeam/cloud-function#44]
<img width="583" alt="Screen Shot 2022-12-09 at 2 33 27 PM" src="https://user-images.githubusercontent.com/49984479/206639791-629ca560-fdc6-4bcb-a26d-9159a0b3a169.png">
如圖 存到字串
另外就是我有把 discount 改成 >= 0 @Lanznx 可幫檢查一下

**Comment by Lanznx** [comment]
@YJack0000 為啥要把 discount 存成字串？

**Comment by YJack0000** [comment]
喔喔我是指他會存成字串，我傳數字他會要我提供數字

**Comment by Lanznx** [comment]
已解決 https://github.com/CeranaTeam/cloud-function/pull/49
