### ISSUE TITLE
discount 要繼承是數字

### ISSUE THREAD

**Issue by YJack0000** [CeranaTeam/cloud-function#65]
![Screen Shot 2022-12-14 at 9 47 38 PM](https://user-images.githubusercontent.com/49984479/207611796-f6121f3f-1536-4e15-bbf9-59d15214cc1f.png)

**Comment by Lanznx** [comment]
跟上一篇 issue 一樣嗎
https://github.com/CeranaTeam/cloud-function/issues/66
