### ISSUE TITLE
startTime endTime not working

### ISSUE THREAD

**Issue by YJack0000** [CeranaTeam/cloud-function#67]
![Screen Shot 2022-12-14 at 9 58 51 PM](https://user-images.githubusercontent.com/49984479/207614487-60743ac1-b986-4494-97e6-7f1fb5a07c26.png)
如圖，上面兩個是 startTime 跟 endTime。而下面 query 出來的卻是有不在範圍內的東西。

**Comment by YJack0000** [comment]
startAt=1670939789000&endAt=1671026189065
可以在測試了時候用這段打 postman 數字跟上面的一樣。應該要拿到 13 號以後的東西。

**Comment by Lanznx** [comment]
@YJack0000  這是 production 的 Get Sell Order 嗎
